credit_transfer/advanced_standing/urls.py
from django.urls import path

from . import views

app_name = 'advanced_standing'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:country_name>/', views.get_partners, name='get_partners'),
    path('institution/<int:partner_id>/', views.get_partner_degrees, name='get_partner_degrees'),
    # path('institution/<int:partner_id>/', views.get_partner_programs, name='get_partner_programs'),
    path('articulations/<int:partner_degree_id>/<int:year>/', views.get_articulations, name='get_articulations'),
    path('study_plan/<int:articulation_id>/<int:year_type>/<int:semester>', views.get_study_plans, name='get_study_plans'),
]

credit_transfer/credit_transfer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('advanced_standing/', include('advanced_standing.urls', namespace='advanced_standing')),
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_transfer/advanced_standing/models.py
import os
from uuid import uuid4
from datetime import datetime
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from smart_selects.db_fields import ChainedForeignKey


class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'


def institution_badge_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join('institution_badge/', filename)


class Partner(models.Model):
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, unique=True)
    abbr = models.CharField(max_length=10, blank=True, verbose_name='Abbreviation')
    description = models.TextField(verbose_name='General information')
    course_mappings = models.TextField(
        blank=True,
        verbose_name='Course mappings',
        help_text='Each line is a mapping in the following format:<br>'
                  '<b>ANU course code; Partner course name 1; Partner course name 2; ...&#8617;</b>'
    )
    url = models.URLField(max_length=200, blank=True, verbose_name='Official website')
    badge = models.ImageField(upload_to=institution_badge_path, null=True, blank=True, verbose_name='Institution badge')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Partner'
        verbose_name_plural = 'Partners'


def get_current_year():
    return datetime.now().year


# Super class of ANUProgram and PartnerProgram
class Program(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        abstract = True


class ANUProgram(Program):
    code = models.CharField(max_length=20, unique=True, verbose_name='Program code')
    duration = models.FloatField(default=4, verbose_name='Normal duration in years')

    def clean(self):
        processed_code = self.code.strip().upper()
        result = ANUProgram.objects.filter(code=processed_code)
        if result.exists():
            obj = result.first()
            if self.name == obj.name and self.duration == obj.duration:
                raise ValidationError('{} already exists in the database.'.format(processed_code))

    def save(self, *args, **kwargs):
        self.code = self.code.strip().upper()
        super(ANUProgram, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        ordering = ['name', 'code']
        verbose_name = 'ANU Program'
        verbose_name_plural = 'ANU Programs'


class ANUMajorOrSpecialisation(models.Model):
    CAREER_CHOICES = (
        ('Undergraduate', 'Undergraduate'),
        ('Postgraduate', 'Postgraduate'),
    )

    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    career = models.CharField(max_length=20, choices=CAREER_CHOICES, default='Undergraduate')

    def clean(self):
        processed_code = self.code.strip().upper()
        result = ANUMajorOrSpecialisation.objects.filter(code=processed_code)
        if result.exists():
            obj = result.first()
            if self.name == obj.name and self.career == obj.career:
                raise ValidationError('{} already exists in the database.'.format(processed_code))

    def save(self, *args, **kwargs):
        self.code = self.code.strip().upper()
        super(ANUMajorOrSpecialisation, self).save(*args, **kwargs)

    def __str__(self):
        return '{} - {}'.format(self.name, self.career)

    class Meta:
        ordering = ['name', 'career']
        unique_together = ('code', 'career')
        verbose_name = 'ANU Major or Specialisation'
        verbose_name_plural = 'ANU Majors or Specialisations'


class ANUDegree(models.Model):
    anu_program = models.ForeignKey(ANUProgram, on_delete=models.CASCADE)
    anu_major_spec = models.ManyToManyField(
        ANUMajorOrSpecialisation,
        blank=True,
        verbose_name='ANU Major or Specialisation'
    )

    def __str__(self):
        if not self.anu_major_spec.exists():
            return '{}'.format(
                self.anu_program.name,
            )
        else:
            return '{} - {}'.format(
                self.anu_program.name,
                ', '.join([m.name for m in self.anu_major_spec.all()]),
            )

    class Meta:
        ordering = ['anu_program']
        verbose_name = 'ANU Degree'
        verbose_name_plural = 'ANU Degrees'


class ANUCourse(models.Model):
    code = models.CharField(max_length=20, unique=True, verbose_name='Course code')
    name = models.CharField(max_length=100)

    def clean(self):
        self.code = self.code.strip().upper()

    def __str__(self):
        return '{} {}'.format(self.code, self.name)

    class Meta:
        ordering = ['code']
        verbose_name = 'ANU Course'
        verbose_name_plural = 'ANU Courses'


class PartnerProgram(Program):
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {}'.format(self.partner.name, self.name)

    class Meta:
        ordering = ['partner', 'name']
        unique_together = ('partner', 'name')
        verbose_name = 'Partner Program'
        verbose_name_plural = 'Partner Programs'


class PartnerDegree(models.Model):
    DEGREE_TYPE_CHOICES = (
        ('Bachelor Degree', 'Bachelor Degree'),
        ('Master Degree', 'Master Degree'),
        ('Diploma', 'Diploma')
    )
    COLLEGE_CHOICES = (
        ('C', 'Computer Science'),
        ('E', 'Engineering'),
    )
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    partner_program = ChainedForeignKey(
        PartnerProgram,
        chained_field='partner',
        chained_model_field='partner',
        show_all=False,
        auto_choose=True,
        sort=False,
        on_delete=models.CASCADE,
    )
    college = models.CharField(max_length=1, choices=COLLEGE_CHOICES, default='C')
    degree_type = models.CharField(max_length=20, choices=DEGREE_TYPE_CHOICES, default='Bachelor Degree')
    major = models.TextField(verbose_name='Major(s)', help_text='Note: one major each line')
    anu_degrees = models.ManyToManyField(ANUDegree, through='Articulation')
    required_courses = models.ManyToManyField(ANUCourse, related_name='required_course', blank=True)
    note = models.TextField(blank=True, verbose_name='Required courses note')

    @property
    def get_majors_abbr(self):
        majors = self.major.split('\r\n')
        if len(majors) < 4:
            return '; '.join(majors)
        else:
            other_majors_str = ' and other {} majors'.format(len(majors) - 3)
            return '; '.join(majors[:3]) + other_majors_str

    def __str__(self):
        return '{} - {} in {}'.format(self.partner_program.partner.name, self.degree_type, self.get_majors_abbr)

    class Meta:
        ordering = ['partner_program', 'degree_type', 'major']
        unique_together = ('partner_program', 'degree_type', 'major')
        verbose_name = 'Partner Degree'
        verbose_name_plural = 'Partner Degrees'


class Articulation(models.Model):
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    partner_degree = ChainedForeignKey(
        PartnerDegree,
        chained_field='partner',
        chained_model_field='partner',
        show_all=False,
        auto_choose=True,
        sort=False,
        on_delete=models.CASCADE,
    )
    year = models.IntegerField(default=get_current_year, verbose_name='Academic year')  # IMPORTANT
    anu_degree = models.ForeignKey(ANUDegree, on_delete=models.CASCADE)
    completed_years = models.FloatField(
        default=2,
        validators=[MinValueValidator(0), MaxValueValidator(4)],
        verbose_name='Completed years in current degree',
        help_text='"0" stands for "Completion"'
    )
    time_to_complete = models.FloatField(
        default=2,
        validators=[MinValueValidator(0), MaxValueValidator(4)],
        verbose_name='Time to Complete Degree at ANU (in years)',
        help_text='"0" stands for "Case-by-case"'
    )
    advanced_standing = models.CharField(
        max_length=100,
        help_text='Example: 1 year (48 units) / 2 years (96 units) / 1.5 years (72 units) / Case-by-case / Entry only'
    )
    requirements = models.TextField(verbose_name='Academic requirements')
    note = models.CharField(
        max_length=300,
        blank=True,
        verbose_name='Note',
        help_text='E.g. Students below an average of 75% are invited to apply. '
                  'However, admission and advance standing will be assessed on a case-by-case basis.'
    )
    advanced_standing_details = models.ManyToManyField(ANUCourse, related_name='advanced_standing_course', blank=True)
    details_note = models.TextField(blank=True, verbose_name='Advanced standing details note')
    rationale = models.TextField(blank=True, verbose_name='Rationale')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    updated_time = models.DateTimeField(auto_now=True, verbose_name='Last updated')

    @property
    def update_date(self):
        return self.updated_time.strftime('%d %B %Y')

    @property
    def get_majors_abbr(self):
        majors = self.partner_degree.major.split('\r\n')
        if len(majors) < 3:
            return '; '.join(majors)
        else:
            other_majors_str = ' and other {} majors'.format(len(majors) - 2)
            return '; '.join(majors[:2]) + other_majors_str

    def __str__(self):
        if not self.anu_degree.anu_major_spec.exists():
            return '{}: {} in {} —— ANU: {} - {}'.format(
                self.partner_degree.partner_program.partner.name,

credit_transfer/advanced_standing/views.py
from django.shortcuts import render
from django.http import Http404
from django.views.decorators.cache import cache_page

from .models import Country, Partner, ANUCourse, PartnerProgram, PartnerDegree, Articulation, StudyPlan
from .utils import *


# @cache_page(60 * 60)
def index(request):
    countries = Country.objects.all()

    # the countries/regions will be displayed in a Nx4 table in the template
    country_list = [countries[i:i + 4] for i in range(0, len(countries), 4)]
    table_empty_cells = range(4 - len(countries) % 4)

    context = {'country_list': country_list, 'table_empty_cells': table_empty_cells}
    return render(request, 'advanced_standing/index.html', context)


# @cache_page(60 * 60)
def get_partners(request, country_name):
    partners = Partner.objects.filter(country__name=country_name)
    if not partners.first():
        raise Http404

    context = {'partners': partners, 'country': country_name}
    return render(request, 'advanced_standing/partners.html', context)


# @cache_page(60 * 15)
def get_partner_degrees(request, partner_id):
    try:
        partner = Partner.objects.get(id=partner_id)
    except Partner.DoesNotExist:
        raise Http404

    comp = PartnerDegree.objects.filter(partner_program__partner__id=partner_id, college='C')
    engi = PartnerDegree.objects.filter(partner_program__partner__id=partner_id, college='E')
    year = get_current_year()

    if comp.first():
        for degree in comp:
            degree.major = get_partner_degree_major_list(degree.major)

    if engi.first():
        for degree in engi:
            degree.major = get_partner_degree_major_list(degree.major)

    context = {'partner': partner, 'comp': comp, 'engi': engi, 'year': year}
    return render(request, 'advanced_standing/partner_degrees.html', context)


# @cache_page(60 * 15)
def get_articulations(request, partner_degree_id, year):
    query_year = year

    # get available years for the selector on the page
    distinct_years = Articulation.objects.filter(partner_degree__id=partner_degree_id).values_list('year', flat=True).distinct().order_by('year')
    year_selector = list(distinct_years)

    # if the year select is empty or the query year is out of valid range, raise 404
    if not year_selector or query_year < year_selector[0] or query_year > get_current_year():
        raise Http404

    artics = Articulation.objects.filter(partner_degree__id=partner_degree_id, year=query_year).order_by('partner_degree', 'anu_degree')

    # if the no articulation exists in queried year, jump to the articulations in the latest year available
    if not artics.first():
        artics = Articulation.objects.filter(partner_degree__id=partner_degree_id, year=year_selector[-1])

    for artic in artics:
        # add urls to the courses of advanced_standing_details and required_courses
        artic.advanced_standing_details_list, artic.has_mappings = append_url_and_mappings_to_courses(
            artic.advanced_standing_details.all(),
            artic.partner.course_mappings
        )
        artic.required_courses_list = append_url_to_courses(artic.partner_degree.required_courses.all())

        # add url to the major_or_spec object if it exists
        artic.ms_list = append_url_to_major_spec(artic.anu_degree.anu_major_spec.all())

        # add url to the anu program
        artic.anu_program = append_url_to_anu_program(artic.anu_degree.anu_program)

        # convert the majors of partner degree to a list
        artic.partner_degree.major = get_partner_degree_major_list(artic.partner_degree.major)

        # check if any study plan with year_type='Any' exists
        if StudyPlan.objects.filter(articulation__id=artic.id, year_type=0).count():
            artic.has_study_plan = True
            artic.has_odd_and_even = False  # doesn't need to differentiate odd and even year
        # check if any study plan with year_type='Odd' exists (if odd year exists, even year must exist)
        # For future developers: you can modify here to be more robust, or modify the the study plan section in
        # articulation template
        elif StudyPlan.objects.filter(articulation__id=artic.id, year_type=1).count() >= 2 and \
                StudyPlan.objects.filter(articulation__id=artic.id, year_type=2).count() >= 2:
            artic.has_study_plan = True
            artic.has_odd_and_even = True
        else:
            artic.has_study_plan = False

    context = {
        'artics': artics,
        'year_selector': year_selector,
        'query_year': query_year,
        'partner_degree_id': partner_degree_id,
    }
    return render(request, 'advanced_standing/articulations.html', context)


# @cache_page(60 * 15)
def get_study_plans(request, articulation_id, year_type, semester):
    studyplans = StudyPlan.objects.filter(articulation__id=articulation_id, year_type=year_type, semester=semester)

    if not studyplans.first():
        raise Http404

    # add attributes for convenience in template
    studyplans.year_type = year_type
    studyplans.semester = semester

    # add urls to the courses and major or spec
    for plan in studyplans:
        ms = append_url_to_major_spec([plan.anu_major_spec])
        plan.major_or_spec = ms[0] if ms else None

        if plan.year1_sem1:
            plan.year1_sem1 = append_url_to_text_courses(plan.year1_sem1)

        if plan.year1_sem2:
            plan.year1_sem2 = append_url_to_text_courses(plan.year1_sem2)

        if plan.year2_sem1:
            plan.year2_sem1 = append_url_to_text_courses(plan.year2_sem1)

        if plan.year2_sem2:
            plan.year2_sem2 = append_url_to_text_courses(plan.year2_sem2)

        if plan.year3_sem1:
            plan.year3_sem1 = append_url_to_text_courses(plan.year3_sem1)

        if plan.year3_sem2:
            plan.year3_sem2 = append_url_to_text_courses(plan.year3_sem2)

        if plan.summer_holiday:
            plan.summer_holiday = append_url_to_summer_holiday_course(plan.summer_holiday)

    context = {'studyplans': studyplans}
    return render(request, 'advanced_standing/study_plans.html', context)

credit_transfer/templates/advanced_standing/articulations.html
{% extends "advanced_standing/base.html" %}
{% load static %}

{% block title %}Articulation Details{% endblock %}

{% block content %}
    <div class="year-selector">
        <label for="query_year">Academic year:
            <select id="query_year" name="query_year" onchange="location.href = this.value;">
                {% for year_option in year_selector %}
                    {% if year_option == query_year %}
                        <option selected>{{ year_option }}</option>
                    {% else %}
                        <option value="{% url 'advanced_standing:get_articulations' partner_degree_id year_option %}">{{ year_option }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="clear"></div>

    <h2 class="page-title-black">Credit Arrangement</h2>
    <h4 class="page-title-left">ANU College of Engineering and Computer Science & {{ artics.first.partner.name }}</h4>

    {% for artic in artics %}
        <div class="articulation-table">
            <table>
                <tr>
                    <th>
                        {% if artic.completed_years == 0 %}
                            Completion of following program
                        {% else %}
                            Completion of {{ artic.completed_years|floatformat }}
                            {% if artic.completed_years > 1 %}
                                years
                            {% else %}
                                year
                            {% endif %}
                            of {{ artic.partner.abbr }} {{ artic.partner_degree.degree_type }} in
                        {% endif %}
                    </th>
                    <th>ANU Degree</th>
                    <th>ANU Normal Duration in years</th>
                    <th>Advanced Standing in years (Credits)</th>
                    <th>Time to complete degree at ANU</th>
                    <th>Academic requirements</th>
                </tr>
                <tr>
                    <td>
                        {{ artic.partner_degree.partner_program.name }} <br>
                        {% for m in artic.partner_degree.major %}
                            &#8226;&nbsp;{{ m }} <br>
                        {% endfor %}
                    </td>
                    <td>
                        {% if artic.anu_program.url %}
                            <a href="{{ artic.anu_program.url }}" target="_blank">{{ artic.anu_program.name }}</a><br>
                        {% else %}
                            {{ artic.anu_program.name }}
                        {% endif %}

                        {% if artic.ms_list %}
                        {% for ms in artic.ms_list %}
                            {% if ms.url %}
                                &#8226;&nbsp;<a href="{{ ms.url }}" target="_blank">{{ ms.name }}</a><br>
                            {% else %}
                                &#8226;&nbsp;{{ ms.name }}<br>
                            {% endif %}
                        {% endfor %}
                        {% endif %}
                    </td>
                    <td>
                        {{ artic.anu_program.duration|floatformat }}
                        {% if artic.anu_program.duration > 1 %}
                            years
                        {% else %}
                            year
                        {% endif %}
                    </td>
                    <td>{{ artic.advanced_standing }}</td>
                    <td>
                        {{ artic.time_to_complete|floatformat }}
                        {% if artic.time_to_complete > 1 %}
                            years
                        {% else %}
                            year
                        {% endif %}
                    </td>
                    <td>{{ artic.requirements|linebreaks }}</td>
                </tr>
            </table>

            <div class="update-date-right">
                Last update: {{ artic.update_date }}
            </div>
            <div class="clear"></div>

            {% if artic.note %}
                <div class="articulation-note">
                    Note: {{ artic.note }}
                </div>
            {% endif %}
        </div>

        {% if artic.has_study_plan %}
            <h4 class="page-title-left">Sample Study Plan</h4>
            {% if artic.has_odd_and_even %}
                <div class="studyplan-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Commencement Year</th>
                                <th colspan="2">Semester Intake</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Odd Year</td>
                                <td><a href="{% url 'advanced_standing:get_study_plans' artic.id 1 1 %}">Semester 1 (February)</a></td>
                                <td><a href="{% url 'advanced_standing:get_study_plans' artic.id 1 2 %}">Semester 2 (July)</a></td>
                            </tr>
                            <tr>
                                <td>Even Year</td>
                                <td><a href="{% url 'advanced_standing:get_study_plans' artic.id 2 1 %}">Semester 1 (February)</a></td>
                                <td><a href="{% url 'advanced_standing:get_study_plans' artic.id 2 2 %}">Semester 2 (July)</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="studyplan-table">
                    <table>
                        <thead>
                            <tr>
                                <th colspan="2">Semester Intake</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><a href="{% url 'advanced_standing:get_study_plans' artic.id 0 1 %}">Semester 1 (February)</a></td>
                                <td><a href="{% url 'advanced_standing:get_study_plans' artic.id 0 2 %}">Semester 2 (July)</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% endif %}
        {% endif %}

        {% if artic.rationale %}
            <h4 class="page-title-left">Rationale</h4>
            <div class="rationale">
                <p>{{ artic.rationale|linebreaks }}</p>
            </div>
        {% endif %}

        {% if artic.advanced_standing_details_list %}
            <h4 class="page-title-left">Advanced Standing Details (credits students will receive)</h4>
            <div id="details" class="courses-table">
                <table>
                {% if artic.has_mappings %}
                    <thead>
                        <tr>
                            <th>Course Code</th>
                            <th>Course Name</th>
                            <th>
                                Equivalent Courses
                                {% if artic.partner.abbr %}
                                    in {{ artic.partner.abbr }}
                                {% endif %}
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for c in artic.advanced_standing_details_list %}
                        <tr>
                            {% if c.url %}
                                <td><a href="{{ c.url }}" target="_blank">{{ c.code }}</a></td>
                                <td><a href="{{ c.url }}" target="_blank">{{ c.name }}</a></td>
                            {% else %}
                                <td>{{ c.code }}</td>
                                <td>{{ c.name }}</td>
                            {% endif %}
                            {% if c.mappings %}
                                <td>{{ c.mappings|linebreaksbr }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                    {% else %}
                        <thead>
                            <tr>
                                <th>Course Code</th>
                                <th>Course Name</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for c in artic.advanced_standing_details_list %}
                            <tr>
                                {% if c.url %}
                                    <td><a href="{{ c.url }}" target="_blank">{{ c.code }}</a></td>
                                    <td><a href="{{ c.url }}" target="_blank">{{ c.name }}</a></td>
                                {% else %}
                                    <td>{{ c.code }}</td>
                                    <td>{{ c.name }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                {% endif %}
                </table>
            </div>
            {% if artic.note %}
                <div class="note">
                    {{ artic.details_note|linebreaks }}
                </div>
            {% endif %}
        {% endif %}

        {% if artic.required_courses_list %}
            <h4 class="page-title-left">In order to comply with the requirements of the articulation program, <br>students will need to do the following courses at ANU</h4>
            <div id="required" class="courses-table">
                <table>
                    <thead>
                        <tr>
                            <th>Course Code</th>
                            <th>Course Name</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for c in artic.required_courses_list %}
                        <tr>
                        {% if c.url %}
                            <td><a href="{{ c.url }}" target="_blank">{{ c.code }}</a></td>
                            <td><a href="{{ c.url }}" target="_blank">{{ c.name }}</a></td>
                        {% else %}
                            <td>{{ c.code }}</td>
                            <td>{{ c.name }}</td>
                        {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            {% if artic.partner_degree.note %}
                <div class="note">
                    {{ artic.partner_degree.note|linebreaks }}
                </div>
            {% endif %}
        {% endif %}
        <br>

    {% endfor %}
{% endblock %}

credit_transfer/templates/advanced_standing/index.html
{% extends "advanced_standing/base.html" %}
{% load static %}

{% block title %}Advanced Standing{% endblock %}

{% block content %}
    <h2 class="page-title">Advanced Standing</h2>
    <a href="https://www.anu.edu.au/study" target="_blank">
        <img id="index-page-img" src="{% static "images/index-page-img.png" %}" alt="index-page-img">
    </a>

    <div class="page-content">
        <p>The ANU College of Engineering & Computer Science partners with a variety of international institutions to give students the opportunity to study at Australia's top university.</p>
        <p>The College welcomes students seeking to obtain advanced standing (or 'credit transfer') into the Bachelor of Engineering, Bachelor of Advanced Computing, Bachelor of Software Engineering, or Bachelor of Information Technology.</p>
        <p>Advanced standing into the Bachelor of Engineering (Research & Development) and Bachelor of Advanced Computing (Research & Development) is not normally permitted and is assessed on a case-by-case basis.</p>
    </div>

    <h2 class="page-title">How much Advanced Standing can students obtain?</h2>

    <div class="page-content">
        <p>Generally, students can receive a maximum of two years of advanced standing into the Bachelor of Engineering, Bachelor of Advanced Computing, or Bachelor Software Engineering and a maximum of one and half years of advanced standing into Bachelor of Information Technology.</p>
        <p>Outside of the College formal advanced standing/credit transfer arrangements (listed below by country/region), the College assesses applications for advanced standing/credit transfer towards its programs based on comparable prior studies at international institutions on a case-by-case basis.</p>
    </div>

    <div id="countries" class="container">
        {% for country_row in country_list %}
            <div class="row">
            {% for country in country_row %}
                    <div class="col"><a href="{% url 'advanced_standing:get_partners' country.name %}">{{ country.name }}</a></div>
            {% endfor %}
            {% if forloop.last %}
                {% for _ in table_empty_cells %}
                    <div class="col"></div>
                {% endfor %}
            {% endif %}
            </div>
        {% endfor %}
    </div>

{% endblock %}

credit_transfer/templates/advanced_standing/partners.html
{% extends "advanced_standing/base.html" %}
{% load static %}

{% block title %}ANU Partner Institution{% endblock %}

{% block content %}
    <h2 class="page-title">Partner Institutions in {{ country }}</h2>

    <div id="partners">
        <table>
            {% for partner in partners %}
                <tr>
                    <td>
                        <div class="partner-badge">
                        {% if partner.badge %}
                            <img src="{{ partner.badge.url }}" alt="Badge">
                        {% else %}
                            University badge not available now
                        {% endif %}
                        </div>
                    </td>

                    <td>
                        <a href="{% url 'advanced_standing:get_partner_degrees' partner.id %}">{{ partner.name }}</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}